# yaml-language-server: $schema=../schemas/development.json

# ANCHOR: all
# The relative path from the config file (or from the cwd, if set via the cli flag)
# to the directory containing templates.
templates_dir: null

# A map of template definitions.
templates: {}

# The configuration for typescript-related commands.
typescript: null

# Various kinds of presets
pre_commit_presets: {}

gitignore_presets: {}

templating_presets: {}

repo_presets: {}

docker_compose_presets: {}

# Extends other configuration files
extends: []

# Variables for templates
vars: {}

# Do not overwrite existing files
no_overwrite: false

# The shell to use for the `exec` command. Defaults to `cmd.exe` on windows and `sh` elsewhere.
shell: null
# ANCHOR_END: all
